import { ComponentModel, ComponentCategory } from '@/types/component';

export const componentCategories: ComponentCategory[] = [
  {
    id: 'mechanical',
    name: 'Mechanical',
    description: 'Bolts, screws, hinges, and mechanical parts',
    icon: 'Cog',
    count: 12,
  },
  {
    id: 'decorative',
    name: 'Decorative',
    description: 'Ornamental and aesthetic components',
    icon: 'Sparkles',
    count: 8,
  },
  {
    id: 'structural',
    name: 'Structural',
    description: 'Beams, panels, and structural elements',
    icon: 'Building2',
    count: 15,
  },
  {
    id: 'electronic',
    name: 'Electronic',
    description: 'Circuit boards, connectors, and electronic parts',
    icon: 'Cpu',
    count: 10,
  },
];

export const sampleComponents: ComponentModel[] = [
  {
    id: 'hex-bolt',
    name: 'Hex Bolt',
    description: 'Standard hexagonal head bolt with threaded shaft',
    category: 'mechanical',
    tags: ['bolt', 'fastener', 'hexagonal', 'threaded'],
    modelPath: '/models/hex-bolt.glb',
    thumbnailPath: 'https://images.pexels.com/photos/162553/keys-workshop-mechanic-tools-162553.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['steel', 'aluminum', 'brass'],
    complexity: 'simple',
    downloadCount: 1247,
    rating: 4.8,
  },
  {
    id: 'door-hinge',
    name: 'Door Hinge',
    description: 'Heavy-duty door hinge with pin mechanism',
    category: 'mechanical',
    tags: ['hinge', 'door', 'hardware', 'pivot'],
    modelPath: '/models/door-hinge.glb',
    thumbnailPath: 'https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['steel', 'brass', 'stainless-steel'],
    complexity: 'medium',
    downloadCount: 892,
    rating: 4.6,
  },
  {
    id: 'metal-panel',
    name: 'Metal Panel',
    description: 'Industrial metal panel with riveted edges',
    category: 'structural',
    tags: ['panel', 'metal', 'industrial', 'riveted'],
    modelPath: '/models/metal-panel.glb',
    thumbnailPath: 'https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['aluminum', 'steel', 'titanium'],
    complexity: 'simple',
    downloadCount: 634,
    rating: 4.4,
  },
  {
    id: 'gear-assembly',
    name: 'Gear Assembly',
    description: 'Mechanical gear system with multiple interconnected gears',
    category: 'mechanical',
    tags: ['gear', 'mechanical', 'assembly', 'rotation'],
    modelPath: '/models/gear-assembly.glb',
    thumbnailPath: 'https://images.pexels.com/photos/159275/macro-gears-cogwheels-engine-159275.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['steel', 'brass', 'plastic'],
    complexity: 'complex',
    downloadCount: 1089,
    rating: 4.9,
  },
  {
    id: 'circuit-board',
    name: 'Circuit Board',
    description: 'Electronic PCB with components and traces',
    category: 'electronic',
    tags: ['pcb', 'electronic', 'circuit', 'board'],
    modelPath: '/models/circuit-board.glb',
    thumbnailPath: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['fiberglass', 'copper', 'plastic'],
    complexity: 'complex',
    downloadCount: 756,
    rating: 4.7,
  },
  {
    id: 'ornate-bracket',
    name: 'Ornate Bracket',
    description: 'Decorative Victorian-style mounting bracket',
    category: 'decorative',
    tags: ['bracket', 'ornate', 'decorative', 'victorian'],
    modelPath: '/models/ornate-bracket.glb',
    thumbnailPath: 'https://images.pexels.com/photos/276514/pexels-photo-276514.jpeg',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    materials: ['brass', 'bronze', 'iron'],
    complexity: 'medium',
    downloadCount: 423,
    rating: 4.3,
  },
];