import { ComponentModel, ComponentCategory } from '@/types/component';

export const componentCategories: ComponentCategory[] = [
  {
    id: 'mechanical',
    name: 'Mechanical',
    description: 'Bolts, screws, hinges, and mechanical parts',
    icon: 'Cog',
    count: 4,
  },
  {
    id: 'decorative',
    name: 'Decorative',
    description: 'Ornamental and aesthetic components',
    icon: 'Sparkles',
    count: 3,
  },
  {
    id: 'structural',
    name: 'Structural',
    description: 'Beams, panels, and structural elements',
    icon: 'Building2',
    count: 1,
  },
  {
    id: 'electronic',
    name: 'Electronic',
    description: 'Circuit boards, connectors, and electronic parts',
    icon: 'Cpu',
    count: 1,
  },
  {
    id: 'geometric',
    name: 'Geometric',
    description: 'Abstract geometric shapes and effects',
    icon: 'Shapes',
    count: 4,
  },
  {
    id: 'futuristic',
    name: 'Futuristic',
    description: 'Sci-fi and advanced technology components',
    icon: 'Zap',
    count: 1,
  },
  {
    id: 'ui',
    name: 'UI Components',
    description: 'Practical UI elements for websites and applications',
    icon: 'Layout',
    count: 0,
  },
];

export const sampleComponents: ComponentModel[] = [
  {
    id: 'hex-bolt',
    name: 'Hex Bolt',
    description: 'Standard hexagonal head bolt with threaded shaft - generated with Three.js primitives',
    category: 'mechanical',
    tags: ['bolt', 'fastener', 'hexagonal', 'threaded', 'mechanical'],
    componentType: 'hex-bolt',
    thumbnailPath: '/components/hexbolt.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['steel', 'aluminum', 'brass'],
    complexity: 'simple',
    downloadCount: 1247,
    rating: 4.8,
    features: ['rotation', 'material-customization', 'scale-control'],
  },
  {
    id: 'door-hinge',
    name: 'Door Hinge',
    description: 'Heavy-duty door hinge with pin mechanism - built with geometric primitives',
    category: 'mechanical',
    tags: ['hinge', 'door', 'hardware', 'pivot', 'mechanical'],
    componentType: 'door-hinge',
    thumbnailPath: '/components/doorhinge.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['steel', 'brass', 'stainless-steel'],
    complexity: 'medium',
    downloadCount: 892,
    rating: 4.6,
    features: ['rotation', 'material-customization', 'scale-control', 'position-control'],
  },
  {
    id: 'metal-panel',
    name: 'Metal Panel',
    description: 'Industrial metal panel with riveted edges - generated geometry',
    category: 'structural',
    tags: ['panel', 'metal', 'industrial', 'riveted', 'structural'],
    componentType: 'metal-panel',
    thumbnailPath: '/components/metalpanel.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['aluminum', 'steel', 'titanium'],
    complexity: 'simple',
    downloadCount: 634,
    rating: 4.4,
    features: ['material-customization', 'scale-control', 'texture-variation'],
  },
  {
    id: 'gear-assembly',
    name: 'Gear Assembly',
    description: 'Mechanical gear system with multiple interconnected gears - procedural generation',
    category: 'mechanical',
    tags: ['gear', 'mechanical', 'assembly', 'rotation', 'procedural'],
    componentType: 'gear-assembly',
    thumbnailPath: '/components/gearassembly.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['steel', 'brass', 'plastic'],
    complexity: 'complex',
    downloadCount: 1089,
    rating: 4.9,
    features: ['rotation', 'material-customization', 'scale-control', 'animation', 'interactive'],
  },
  {
    id: 'circuit-board',
    name: 'Circuit Board',
    description: 'Electronic PCB with components and traces - procedural geometry',
    category: 'electronic',
    tags: ['pcb', 'electronic', 'circuit', 'board', 'procedural'],
    componentType: 'circuit-board',
    thumbnailPath: '/components/circuitboard.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['fiberglass', 'copper', 'plastic'],
    complexity: 'complex',
    downloadCount: 756,
    rating: 4.7,
    features: ['emissive', 'material-customization', 'scale-control', 'animation'],
  },
  {
    id: 'ornate-bracket',
    name: 'Ornate Bracket',
    description: 'Decorative Victorian-style mounting bracket - geometric construction',
    category: 'decorative',
    tags: ['bracket', 'ornate', 'decorative', 'victorian', 'geometric'],
    componentType: 'ornate-bracket',
    thumbnailPath: '/components/ornatebracket.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['brass', 'bronze', 'iron'],
    complexity: 'medium',
    downloadCount: 423,
    rating: 4.3,
    features: ['material-customization', 'scale-control', 'detail-variation'],
  },
  {
    id: 'floating-sphere',
    name: 'Floating Sphere',
    description: 'Animated floating sphere with particle effects and glow',
    category: 'geometric',
    tags: ['sphere', 'floating', 'particles', 'glow', 'animation'],
    componentType: 'floating-sphere',
    thumbnailPath: '/components/floatingsphere.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'metal', 'emissive'],
    complexity: 'medium',
    downloadCount: 2156,
    rating: 4.9,
    features: ['floating-animation', 'particle-effects', 'glow', 'material-customization'],
  },
  {
    id: 'geometric-cube',
    name: 'Geometric Cube',
    description: 'Interactive geometric cube with distortion effects',
    category: 'geometric',
    tags: ['cube', 'geometric', 'distortion', 'interactive', 'effects'],
    componentType: 'geometric-cube',
    thumbnailPath: '/components/geometriccube.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'metal', 'emissive'],
    complexity: 'simple',
    downloadCount: 1892,
    rating: 4.7,
    features: ['rotation', 'distortion', 'material-customization', 'interactive'],
  },
  {
    id: 'wireframe-sphere',
    name: 'Wireframe Sphere',
    description: 'Wireframe sphere with animated vertices and connections',
    category: 'geometric',
    tags: ['wireframe', 'sphere', 'vertices', 'animation', 'geometric'],
    componentType: 'wireframe-sphere',
    thumbnailPath: '/components/wireframesphere.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['emissive', 'wireframe', 'neon'],
    complexity: 'medium',
    downloadCount: 1347,
    rating: 4.6,
    features: ['wireframe-animation', 'vertex-effects', 'emissive', 'rotation'],
  },
  {
    id: 'cube',
    name: 'Cube',
    description: 'Basic 3D cube primitive, perfect for prototyping and layouts.',
    category: 'geometric',
    tags: ['cube', 'box', 'primitive', 'geometry', 'basic'],
    componentType: 'cube',
    thumbnailPath: '/components/cube.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 3200,
    rating: 4.8,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'sphere',
    name: 'Sphere',
    description: 'Smooth 3D sphere primitive for a variety of uses.',
    category: 'geometric',
    tags: ['sphere', 'ball', 'primitive', 'geometry', 'basic'],
    componentType: 'sphere',
    thumbnailPath: '/components/sphere.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 2950,
    rating: 4.7,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'torus',
    name: 'Torus',
    description: 'Donut-shaped torus primitive, great for rings and handles.',
    category: 'geometric',
    tags: ['torus', 'donut', 'ring', 'primitive', 'geometry'],
    componentType: 'torus',
    thumbnailPath: '/components/torus.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 2100,
    rating: 4.6,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'cone',
    name: 'Cone',
    description: '3D cone primitive for spikes, trees, and more.',
    category: 'geometric',
    tags: ['cone', 'primitive', 'geometry', 'basic'],
    componentType: 'cone',
    thumbnailPath: '/components/cone.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 1800,
    rating: 4.5,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'plane',
    name: 'Plane',
    description: 'Flat 2D plane for floors, backgrounds, and more.',
    category: 'geometric',
    tags: ['plane', 'flat', 'primitive', 'geometry', 'basic'],
    componentType: 'plane',
    thumbnailPath: '/components/plane.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 170,
    rating: 4.4,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'text-3d',
    name: '3D Text',
    description: 'Customizable 3D text for labels, titles, and UI.',
    category: 'decorative',
    tags: ['text', 'label', 'ui', 'decorative', 'font'],
    componentType: 'text-3d',
    thumbnailPath: '/components/3dtext.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'medium',
    downloadCount: 2500,
    rating: 4.8,
    features: ['text-customization', 'material-customization', 'scale-control'],
  },
  {
    id: 'directional-light',
    name: 'Directional Light',
    description: 'Adjustable directional light for scene illumination.',
    category: 'electronic',
    tags: ['light', 'directional', 'illumination', 'scene', 'electronic'],
    componentType: 'directional-light',
    thumbnailPath: '/components/directionallight.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['light'],
    complexity: 'simple',
    downloadCount: 2100,
    rating: 4.7,
    features: ['intensity-control', 'color-customization', 'direction-control'],
  },
  {
    id: 'perspective-camera',
    name: 'Perspective Camera',
    description: 'Configurable perspective camera for 3D scenes.',
    category: 'electronic',
    tags: ['camera', 'perspective', 'view', 'scene', 'electronic'],
    componentType: 'perspective-camera',
    thumbnailPath: '/components/perspectivecamera.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['camera'],
    complexity: 'simple',
    downloadCount: 1800,
    rating: 4.6,
    features: ['fov-control', 'position-control', 'rotation-control'],
  },
  {
    id: 'grid-helper',
    name: 'Grid Helper',
    description: 'Reference grid for scene alignment and layout.',
    category: 'structural',
    tags: ['grid', 'helper', 'reference', 'structural', 'layout'],
    componentType: 'grid-helper',
    thumbnailPath: '/components/gridhelper.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['grid'],
    complexity: 'simple',
    downloadCount: 1600,
    rating: 4.5,
    features: ['size-control', 'color-customization'],
  },
  {
    id: 'axes-helper',
    name: 'Axes Helper',
    description: 'XYZ axes helper for orientation and debugging.',
    category: 'structural',
    tags: ['axes', 'helper', 'reference', 'structural', 'debug'],
    componentType: 'axes-helper',
    thumbnailPath: '/components/axeshelper.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['axes'],
    complexity: 'simple',
    downloadCount: 1500,
    rating: 4.4,
    features: ['size-control', 'color-customization'],
  },
  {
    id: 'cylinder',
    name: 'Cylinder',
    description: 'A basic 3D cylinder primitive for columns, rods, and more.',
    category: 'geometric',
    tags: ['cylinder', 'primitive', 'geometry', 'column', 'rod'],
    componentType: 'cylinder',
    thumbnailPath: '/components/cylinder.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 1200,
    rating: 4.6,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'pyramid',
    name: 'Pyramid',
    description: 'A 3D pyramid primitive for architectural and decorative uses.',
    category: 'geometric',
    tags: ['pyramid', 'primitive', 'geometry', 'decorative'],
    componentType: 'pyramid',
    thumbnailPath: '/components/pyramid.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['stone', 'glass', 'metal'],
    complexity: 'simple',
    downloadCount: 900,
    rating: 4.5,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'capsule',
    name: 'Capsule',
    description: 'A capsule shape for pills, handles, and more.',
    category: 'geometric',
    tags: ['capsule', 'primitive', 'geometry', 'pill', 'handle'],
    componentType: 'capsule',
    thumbnailPath: '/components/capsule.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'metal', 'glass'],
    complexity: 'simple',
    downloadCount: 800,
    rating: 4.4,
    features: ['scale-control', 'material-customization', 'rotation'],
  },
  {
    id: 'hero-block',
    name: 'Hero Block',
    description: 'A customizable 3D hero block for landing pages and showcases.',
    category: 'decorative',
    tags: ['hero', 'block', 'showcase', 'landing', 'custom'],
    componentType: 'hero-block',
    thumbnailPath: '/components/heroblock.png',
    defaultScale: [1.5, 0.5, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'metal', 'emissive'],
    complexity: 'medium',
    downloadCount: 1500,
    rating: 4.8,
    features: ['scale-control', 'material-customization', 'glow', 'animation'],
  },
  {
    id: 'showcase-card',
    name: 'Showcase Card',
    description: 'A 3D card for bento layouts, product showcases, and more.',
    category: 'decorative',
    tags: ['showcase', 'card', 'bento', 'ui', 'custom'],
    componentType: 'showcase-card',
    thumbnailPath: '/components/showcasecard.png',
    defaultScale: [1.2, 0.2, 0.8],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'metal', 'plastic'],
    complexity: 'medium',
    downloadCount: 1100,
    rating: 4.7,
    features: ['scale-control', 'material-customization', 'shadow', 'animation'],
  },
  {
    id: 'holographic-display',
    name: 'Holographic Display',
    description: 'Futuristic holographic projection with floating data visualization',
    category: 'futuristic',
    tags: ['hologram', 'display', 'futuristic', 'projection', 'data'],
    componentType: 'holographic-display',
    thumbnailPath: '/components/holographicdisplay.png',
    defaultScale: [1.5, 1, 0.1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['holographic', 'glass', 'emissive'],
    complexity: 'complex',
    downloadCount: 1850,
    rating: 4.9,
    features: ['holographic-animation', 'data-visualization', 'emissive', 'interactive'],
  },
  {
    id: 'energy-core',
    name: 'Energy Core',
    description: 'Pulsing energy core with rotating rings and particle effects',
    category: 'futuristic',
    tags: ['energy', 'core', 'pulsing', 'particles', 'futuristic'],
    componentType: 'energy-core',
    thumbnailPath: '/components/energycore.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['energy', 'emissive', 'glass'],
    complexity: 'complex',
    downloadCount: 2200,
    rating: 4.8,
    features: ['pulsing-animation', 'rotating-rings', 'particle-effects', 'energy-glow'],
  },
  {
    id: 'neon-sign',
    name: 'Neon Sign',
    description: 'Glowing neon sign with customizable text and effects',
    category: 'decorative',
    tags: ['neon', 'sign', 'glow', 'text', 'decorative'],
    componentType: 'neon-sign',
    thumbnailPath: '/components/neonsign.png',
    defaultScale: [2, 0.5, 0.1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['neon', 'emissive', 'glass'],
    complexity: 'medium',
    downloadCount: 1680,
    rating: 4.7,
    features: ['text-customization', 'neon-glow', 'flicker-animation', 'color-control'],
  },
  {
    id: 'floating-island',
    name: 'Floating Island',
    description: 'Mystical floating island with cascading waterfalls, trees, and magical particles',
    category: 'decorative',
    tags: ['island', 'floating', 'nature', 'mystical', 'decorative', 'magical'],
    componentType: 'floating-island',
    thumbnailPath: '/components/floatingisland.png',
    defaultScale: [2, 1, 2],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['stone', 'grass', 'water', 'wood', 'magical'],
    complexity: 'complex',
    downloadCount: 2100,
    rating: 4.9,
    features: ['floating-animation', 'waterfall-effects', 'vegetation', 'particle-effects', 'magical-glow'],
  },
  {
    id: 'portal-gate',
    name: 'Portal Gate',
    description: 'Sci-fi portal with swirling energy and dimensional effects',
    category: 'futuristic',
    tags: ['portal', 'gate', 'dimensional', 'energy', 'futuristic'],
    componentType: 'portal-gate',
    thumbnailPath: '/components/portalgate.png',
    defaultScale: [1.5, 2, 0.3],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['energy', 'metal', 'emissive'],
    complexity: 'complex',
    downloadCount: 1950,
    rating: 4.9,
    features: ['portal-animation', 'energy-swirl', 'dimensional-effects', 'emissive'],
  },
  {
    id: 'crystal-cluster',
    name: 'Crystal Cluster',
    description: 'Geometric crystal formation with prismatic light effects',
    category: 'geometric',
    tags: ['crystal', 'cluster', 'prismatic', 'geometric', 'light'],
    componentType: 'crystal-cluster',
    thumbnailPath: '/components/crystalcluster.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['crystal', 'glass', 'emissive'],
    complexity: 'medium',
    downloadCount: 1320,
    rating: 4.6,
    features: ['prismatic-effects', 'light-refraction', 'crystal-growth', 'material-customization'],
  },
  {
    id: 'steampunk-engine',
    name: 'Steampunk Engine',
    description: 'Enhanced Victorian-style steam engine with animated pistons, rotating gears, pressure gauges, steam effects, and detailed mechanical components',
    category: 'mechanical',
    tags: ['steampunk', 'engine', 'pistons', 'gears', 'mechanical', 'valves', 'animation', 'steam'],
    componentType: 'steampunk-engine',
    thumbnailPath: '/components/steampunkengine.png',
    defaultScale: [1.2, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['brass', 'copper', 'steel', 'iron'],
    complexity: 'complex',
    downloadCount: 1850,
    rating: 4.9,
    features: ['piston-animation', 'gear-rotation', 'steam-effects', 'mechanical-movement', 'pressure-gauges', 'flywheel-spin', 'cooling-fins', 'crankshaft', 'oil-reservoir'],
  },
  {
    id: 'data-sphere',
    name: 'Data Sphere',
    description: 'Interactive data visualization sphere with flowing information streams',
    category: 'futuristic',
    tags: ['data', 'sphere', 'visualization', 'information', 'futuristic'],
    componentType: 'data-sphere',
    thumbnailPath: '/components/datasphere.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['holographic', 'emissive', 'glass'],
    complexity: 'complex',
    downloadCount: 2100,
    rating: 4.8,
    features: ['data-streams', 'interactive', 'holographic', 'information-flow'],
  },
  {
    id: 'magnetic-field',
    name: 'Magnetic Field',
    description: 'Visual representation of magnetic field lines with particle flow',
    category: 'futuristic',
    tags: ['magnetic', 'field', 'particles', 'physics', 'futuristic'],
    componentType: 'magnetic-field',
    thumbnailPath: '/components/magneticfield.png',
    defaultScale: [1.5, 1.5, 1.5],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['energy', 'emissive', 'field'],
    complexity: 'medium',
    downloadCount: 890,
    rating: 4.5,
    features: ['field-lines', 'particle-flow', 'magnetic-effects', 'physics-simulation'],
  },
  {
    id: 'quantum-cube',
    name: 'Quantum Cube',
    description: 'Quantum superposition cube with probability waves, entanglement lines, and energy field',
    category: 'geometric',
    tags: ['quantum', 'cube', 'superposition', 'probability', 'geometric', 'entanglement'],
    componentType: 'quantum-cube',
    thumbnailPath: '/components/quantumcube.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['quantum', 'emissive', 'glass', 'energy'],
    complexity: 'complex',
    downloadCount: 1950,
    rating: 4.8,
    features: ['superposition-effects', 'probability-waves', 'quantum-animation', 'interactive', 'entanglement-lines'],
  },
  {
    id: 'time-machine',
    name: 'Time Machine',
    description: 'Steampunk time travel device with spinning rings and energy effects',
    category: 'futuristic',
    tags: ['time', 'machine', 'travel', 'steampunk', 'futuristic'],
    componentType: 'time-machine',
    thumbnailPath: '/components/timemachine.png',
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['brass', 'copper', 'energy'],
    complexity: 'complex',
    downloadCount: 1780,
    rating: 4.8,
    features: ['time-effects', 'spinning-rings', 'energy-portal', 'steampunk-design'],
  },
  {
    id: 'neural-network',
    name: 'Neural Network',
    description: '3D neural network visualization with structured layers and animated data flow',
    category: 'futuristic',
    tags: ['neural', 'network', 'ai', 'connections', 'futuristic', 'layers'],
    componentType: 'neural-network',
    thumbnailPath: '/components/neuralnetwork.png',
    defaultScale: [1.5, 1.5, 1.5],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['neural', 'emissive', 'energy', 'holographic'],
    complexity: 'complex',
    downloadCount: 2200,
    rating: 4.9,
    features: ['neural-connections', 'node-animation', 'data-flow', 'ai-visualization', 'structured-layers'],
  },
  {
    id: 'crystal-prism',
    name: 'Crystal Prism',
    description: 'Geometric prism with light refraction and rainbow effects',
    category: 'geometric',
    tags: ['prism', 'crystal', 'light', 'refraction', 'geometric'],
    componentType: 'crystal-prism',
    thumbnailPath: '/components/crystalprism.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['crystal', 'glass', 'prismatic'],
    complexity: 'medium',
    downloadCount: 1150,
    rating: 4.5,
    features: ['light-refraction', 'rainbow-effects', 'crystal-clear', 'optical-effects'],
  },
  {
    id: 'plasma-ball',
    name: 'Plasma Ball',
    description: 'Interactive plasma ball with realistic electric arcs, energy tendrils, and floating particles',
    category: 'futuristic',
    tags: ['plasma', 'ball', 'electric', 'arcs', 'futuristic', 'energy'],
    componentType: 'plasma-ball',
    thumbnailPath: '/components/plasmaball.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plasma', 'emissive', 'glass', 'energy'],
    complexity: 'complex',
    downloadCount: 2400,
    rating: 4.9,
    features: ['plasma-arcs', 'electric-effects', 'interactive', 'energy-tendrils', 'floating-particles'],
  },
  {
    id: 'fractal-tree',
    name: 'Fractal Tree',
    description: 'Mathematical fractal tree with recursive branching patterns and natural growth',
    category: 'geometric',
    tags: ['fractal', 'tree', 'mathematical', 'recursive', 'geometric', 'natural'],
    componentType: 'fractal-tree',
    thumbnailPath: '/components/fractaltree.png',
    defaultScale: [1, 2, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['wood', 'emissive', 'nature', 'organic'],
    complexity: 'complex',
    downloadCount: 1850,
    rating: 4.8,
    features: ['fractal-patterns', 'recursive-branching', 'mathematical', 'growth-animation', 'natural-particles'],
  },
  {
    id: 'holographic-ui',
    name: 'Holographic UI',
    description: 'Futuristic user interface with floating panels and data displays',
    category: 'futuristic',
    tags: ['holographic', 'ui', 'interface', 'panels', 'futuristic'],
    componentType: 'holographic-ui',
    thumbnailPath: '/components/holographicui.png',
    defaultScale: [2, 1.5, 0.1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['holographic', 'glass', 'emissive'],
    complexity: 'complex',
    downloadCount: 1850,
    rating: 4.8,
    features: ['floating-panels', 'data-displays', 'holographic-effects', 'interactive-ui'],
  },
  {
    id: 'modern-card',
    name: 'Modern Card',
    description: 'Sleek 3D card component perfect for product showcases and portfolios',
    category: 'ui',
    tags: ['card', 'modern', 'ui', 'showcase', 'portfolio'],
    componentType: 'modern-card',
    thumbnailPath: '/components/moderncard.png',
    defaultScale: [1.2, 0.8, 1.5],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'metal', 'plastic'],
    complexity: 'simple',
    downloadCount: 3200,
    rating: 4.9,
    features: ['floating-animation', 'glossy-effect', 'shadow', 'accent-line'],
  },
  {
    id: 'floating-button',
    name: 'Floating Button',
    description: 'Interactive floating action button with glow effects and smooth animations',
    category: 'ui',
    tags: ['button', 'floating', 'action', 'ui', 'interactive'],
    componentType: 'floating-button',
    thumbnailPath: '/components/floatingbutton.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['glass', 'emissive', 'metal'],
    complexity: 'simple',
    downloadCount: 2800,
    rating: 4.8,
    features: ['floating-animation', 'glow-effect', 'shadow', 'rotation'],
  },
  {
    id: 'progress-bar',
    name: 'Progress Bar',
    description: '3D progress indicator with glowing fill and professional appearance',
    category: 'ui',
    tags: ['progress', 'bar', 'indicator', 'ui', 'loading'],
    componentType: 'progress-bar',
    thumbnailPath: '/components/progressbar.png',
    defaultScale: [1.5, 0.8, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['plastic', 'emissive', 'metal'],
    complexity: 'simple',
    downloadCount: 2100,
    rating: 4.7,
    features: ['glow-effect', 'fill-animation', 'professional', 'clean'],
  },
  {
    id: 'notification-badge',
    name: 'Notification Badge',
    description: 'Animated notification counter with pulse effects and glowing appearance',
    category: 'ui',
    tags: ['notification', 'badge', 'counter', 'ui', 'alert'],
    componentType: 'notification-badge',
    thumbnailPath: '/components/notificationbadge.png',
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
    defaultPosition: [0, 0, 0],
    materials: ['emissive', 'glass', 'plastic'],
    complexity: 'medium',
    downloadCount: 1800,
    rating: 4.6,
    features: ['pulse-animation', 'glow-effect', 'floating', 'attention-grabbing'],
  },
];

// Update the counts in componentCategories accordingly
componentCategories.forEach((cat) => {
  cat.count = sampleComponents.filter((c) => c.category === cat.id).length;
});